resources:
  repositories:
  - repository: product
    type: git
    name: Build and Deployment/product
    ref: main
    trigger:
    - main
    - rc
  - repository: brand
    type: git
    name: Build and Deployment/brand
    ref: main
    trigger:
    - rc
  - repository: ncad
    endpoint: JSevillaOog-JLabradaOrg
    type: git
    name: JSevilla0055/Ncad

pool: default

steps:
- checkout: self
- checkout: product
- checkout: brand
- checkout: ncad
- script: dir $(Build.SourcesDirectory)