resources:
  repositories:
  - repository: tools
    type: git
    name: Build and Deployment/product
    ref: main
    trigger:
    - main
    - rc
  - repository: tools
    type: git
    name: Build and Deployment/brand
    ref: main

pool: default

steps:
- checkout: self
- checkout: product
- checkout: brand
- script: dir $(Build.SourcesDirectory)